apiVersion: v1
kind: ConfigMap
metadata:
  name: mlr-dev-rds-cm
  namespace: mlr-dev-rds-ns
data:
  redis-primary.conf: |
    bind 0.0.0.0
    port 6379
  redis-replica.conf: |
    bind 0.0.0.0
    port 6379
