apiVersion: v1
kind: ConfigMap
metadata:
  name: mlr-dev-rds-cm-snt
  namespace: mlr-dev-rds-ns
data:
  setup-sentinel.sh: |
    #!/bin/sh
    MASTER_IP=$(nslookup mlr-dev-rds-sts-0.mlr-dev-rds-svc.mlr-dev-rds-ns.svc.cluster.local | awk '/^Address: / { print $2 }')
    if [ -z "$MASTER_IP" ]; then
      echo "Could not resolve Redis master IP"
      exit 1
    fi

    cat <<EOF > /mnt/sentinel/sentinel.conf
    port 26379
    sentinel monitor mymaster $MASTER_IP 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel parallel-syncs mymaster 1
    sentinel failover-timeout mymaster 10000
    EOF
