apiVersion: v1
kind: Secret
metadata:
  name: mlr-prd-be-sec-nod
  namespace: mlr-prd-be-ns
type: Opaque
data:
  MYSQL_USER: bnlhbQ==                         # nyam (base64 인코딩)
  MYSQL_PASSWORD: azhzcGFzcyM=                 # k8spass# (base64 인코딩)
  MYSQL_DATABASE: bWxyLWRldi1kYi10bGI=
  KAKAO_CLIENT_ID: NWZmMjk0MmYyNmE0ZTYwOGMxZmU4YzU0NDMzNDRlNGI=
  KAKAO_CLIENT_SECRET: NkdMR3dqTm9TMW9qOTN3V3g1RjF3a1pkQTV4M0FSRGo=
  NAVER_CLIENT_ID: cDhSMzJVRlZFbGR2Q1VjdWI5QksK
  NAVER_CLIENT_SECRET: Y0dfcFV6Q3pJRw==
  GOOGLE_CLIENT_ID: MTA3MjY2Nzk0MzM1Ni12OGE0dW9rNjlxMjd2YWNtNGtvcWZqdG1mb3A1MXRqcS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==
  GOOGLE_CLIENT_SECRET: R09DU1BYLVFhNzdSOGJncTMyOTd3MEJYZFozekRzUFc1R0c=
---
apiVersion: v1
kind: Secret
metadata:
  name: mlr-prd-be-sec-fap
  namespace: mlr-prd-be-ns
type: Opaque
data:
  YOUTUBE_API_KEY: QUl6YVN5RDQtcXl6Y1gyam5zMElkR2tiUmVlT1FUWXFuNUE5RjNJ
---
apiVersion: v1
kind: Secret
metadata:
  name: mlr-prd-db-sec
  namespace: mlr-prd-db-ns
data:
  MYSQL_ROOT_PASSWORD: azhzcGFzcyM=            # k8spass#
  MYSQL_DATABASE: bWxyLWRldi1kYi10bGI=         # mlr-prd-db-tlb
  MYSQL_USER: bnlhbQ==                        # nyam
  MYSQL_PASSWORD: azhzcGFzcyM=                      # k8spass# (base64 인코딩)

