apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlr-dev-db-pvc
  namespace: mlr-dev-db-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath