apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlr-prd-db-pvc
  namespace: mlr-prd-db-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-sc