apiVersion: v1
kind: LimitRange
metadata:
  name: mlr-prd-fe-lr
  namespace: mlr-prd-fe-ns
spec:
  limits:
  - default:
      cpu: 500m
      memory: 768Mi
    defaultRequest:
      cpu: 250m
      memory: 384Mi
    type: Container
    max:
      cpu: 1
      memory: 1.5Gi
    min:
      cpu: 100m
      memory: 128Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mlr-prd-be-lr
  namespace: mlr-prd-be-ns
spec:
  limits:
  - type: Container
    default:
      cpu: 600m
      memory: 1Gi
    defaultRequest:
      cpu: 300m
      memory: 512Mi
    max:
      cpu: 2
      memory: 4Gi
    min:
      cpu: 100m
      memory: 128Mi