apiVersion: v1
kind: LimitRange
metadata:
  name: mlr-dev-fe-lr
  namespace: mlr-dev-fe-ns
spec:
  limits:
  - default:
      cpu: 300m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mlr-dev-be-lr
  namespace: mlr-dev-be-ns
spec:
  limits:
  - type: Container
    default:
      cpu: 600m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 128Mi
    max:
      cpu: 2
      memory: 2Gi
    min:
      cpu: 100m
      memory: 64Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mlr-dev-db-lr
  namespace: mlr-dev-db-ns
spec:
  limits:
  - type: Container
    default:
      cpu: 1
      memory: 2Gi
    defaultRequest:
      cpu: 500m
      memory: 1Gi
    max:
      cpu: 2
      memory: 4Gi
    min:
      cpu: 100m
      memory: 128Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mlr-dev-rds-lr
  namespace: mlr-dev-rds-ns
spec:
  limits:
  - type: Container
    default:
      cpu: 200m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: 500m
      memory: 1Gi
    min:
      cpu: 50m
      memory: 64Mi