apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlr-dev-fe-rq
  namespace: mlr-dev-fe-ns
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlr-dev-be-rq
  namespace: mlr-dev-be-ns
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 8Gi
    limits.cpu: "16"
    limits.memory: 16Gi