apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlr-prd-fe-rq
  namespace: mlr-prd-fe-ns
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlr-prd-be-rq
  namespace: mlr-prd-be-ns
spec:
  hard:
    requests.cpu: "5"
    requests.memory: 10Gi
    limits.cpu: "10"
    limits.memory: 20Gi