apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlr-dev-fe-rq
  namespace: mlr-dev-fe-ns
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 1.2Gi
    limits.cpu: "4"
    limits.memory: 2Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlr-dev-be-rq
  namespace: mlr-dev-be-ns
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 6Gi
    limits.cpu: "12"
    limits.memory: 12Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlr-dev-db-rq
  namespace: mlr-dev-db-ns
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlr-dev-rds-rq
  namespace: mlr-dev-rds-ns
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi