apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlr-dev-be-dpl-fap
  namespace: mlr-dev-be-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: 192.168.56.200/mylittlerecipebook/busybox:1.31
          command: ['sh', '-c', "until nslookup mlr-dev-rds-svc.redis.svc.cluster.local; do echo waiting for redis; sleep 2; done"]
      containers:
        - name: backend
          image: 192.168.56.200/mylittlerecipebook/mlr-dev-be-img-fap:8
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: mlr-dev-be-cm-fap
          env:
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mlr-dev-be-sec-fap
                  key: YOUTUBE_API_KEY
