apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlr-prd-be-dpl-fap
  namespace: mlr-prd-be-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: 192.168.56.200/mylittlerecipebook/busybox:1.31
          command: ['sh', '-c', "until nslookup mlr-prd-db-svc-sfs.mlr-prd-db-ns.svc.cluster.local; do echo waiting for db; sleep 2; done"]
      containers:
        - name: backend
          image: 192.168.56.200/mylittlerecipebook/mlr-prd-be-img-fap:5
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mlr-prd-be-sec-fap
                  key: YOUTUBE_API_KEY
