apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlr-dev-be-dpl-fap
  namespace: mlr-dev-be-ns
spec:
  selector:
    matchLabels:
      app: backend
      tier: fast
  template:
    metadata:
      labels:
        app: backend
        tier: fast
    spec:
      initContainers:
        - name: wait-for-redis
          image: 192.168.56.200/mylittlerecipebook/busybox:1.31
          command: ['sh', '-c', "until nslookup mlr-dev-rds-svc.mlr-dev-rds-ns.svc.cluster.local; do echo waiting for redis; sleep 2; done"]
      containers:
        - name: backend
          image: 192.168.56.200/mylittlerecipebook/mlr-dev-be-img-fap:30
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: mlr-dev-be-cm-fap
          env:
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mlr-dev-be-sec-fap
                  key: YOUTUBE_API_KEY
          resources:
            requests:
              cpu: 150m
              memory: 96Mi
            limits:
              cpu: 400m
              memory: 192Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
