apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlr-prd-be-dpl-fap
  namespace: mlr-prd-be-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      tier: fast
  template:
    metadata:
      labels:
        app: backend
        tier: fast
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: mlr-prd-eks-app-ng
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - fast
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: wait-for-redis
          image: 761278642645.dkr.ecr.ap-northeast-2.amazonaws.com/mylittlerecipebook/busybox:1.31
          command: ['sh', '-c', "until nslookup mlr-prd-rds-svc.mlr-prd-rds-ns.svc.cluster.local; do echo waiting for redis; sleep 2; done"]
      containers:
        - name: backend
          image: 761278642645.dkr.ecr.ap-northeast-2.amazonaws.com/mylittlerecipebook/mlr-prd-be-img-fap:10
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: mlr-prd-be-cm-fap
          env:
            - name: YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mlr-prd-be-sec-fap
                  key: YOUTUBE_API_KEY
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
