apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlr-dev-be-dpl-ocr
  namespace: mlr-dev-be-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      tier: ocr
  template:
    metadata:
      labels:
        app: backend
        tier: ocr
    spec:
	  initContainers:
        - name: wait-for-ocr
          image: 192.168.56.200/mylittlerecipebook/busybox:1.31
          command: ['sh', '-c', "until nslookup mlr-dev-ocr-svc.mlr-dev-ocr-ns.svc.cluster.local; do echo waiting for redis; sleep 2; done"]
      containers:
        - name: ocr-backend
          image: 192.168.56.200/mylittlerecipebook/mlr-dev-be-img-ocr
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
