apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlr-prd-be-dpl-ocr
  namespace: mlr-prd-be-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      tier: ocr
  template:
    metadata:
      labels:
        app: backend
        tier: ocr
    spec:
      initContainers:
        - name: wait-for-db
          image: 761278642645.dkr.ecr.ap-northeast-2.amazonaws.com/mylittlerecipebook/busybox:1.31
          command: ['sh', '-c', "until nslookup mlr-prd-db-svc.mlr-prd-db-ns.svc.cluster.local; do echo waiting for db; sleep 2; done"]
      containers:
        - name: ocr-backend
          image: 761278642645.dkr.ecr.ap-northeast-2.amazonaws.com/mylittlerecipebook/mlr-prd-be-img-ocr
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
