version: 0.2

phases:
  install:
    commands:
      - set -e
      - echo "Setting up AWS CLI credentials..."
      - mkdir -p ~/.aws
      - echo "[default]" > ~/.aws/credentials
      - echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
      - echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
      - echo "[default]" > ~/.aws/config
      - echo "region=${AWS_REGION}" >> ~/..aws/config
      - echo "AWS CLI credentials and config:"
      - cat ~/.aws/credentials
      - cat ~/.aws/config

      - echo "Verifying environment variables..."
      - echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
      - echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
      - echo "AWS_REGION: $AWS_REGION"

      - echo "Verifying AWS CLI credentials..."
      - aws sts get-caller-identity || { echo 'AWS CLI credentials verification failed'; exit 1; }
      - echo "AWS CLI credentials are valid."

      - echo "Testing access to S3..."
      - aws s3 ls || { echo 'S3 access test failed'; exit 1; }

      - echo "Setting up kubectl..."
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/

      - echo "Setting up aws-iam-authenticator..."
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mv ./aws-iam-authenticator /usr/local/bin/

      - echo "Verifying aws-iam-authenticator installation..."
      - aws-iam-authenticator version || { echo 'aws-iam-authenticator installation failed'; exit 1; }

      - echo "kubectl version"
      - kubectl version --client

  pre_build:
    commands:
      - set -e
      - echo "Verifying EKS cluster access..."
      - aws eks describe-cluster --region ${AWS_REGION} --name mlr-prd-eks-cls --debug

      - echo "Setting up kubeconfig..."
      - aws eks update-kubeconfig --region ${AWS_REGION} --name mlr-prd-eks-cls || { echo 'kubeconfig update failed'; exit 1; }

      - echo "Kubeconfig file contents:"
      - cat ~/.kube/config
      - kubectl config current-context

      - echo "Debugging kubectl configuration..."
      - kubectl config view
      - kubectl config current-context

      - echo "Getting Kubernetes nodes..."
      - kubectl get nodes || { echo 'kubectl get nodes failed'; kubectl config view; kubectl config current-context; exit 1; }

  build:
    commands:
      - set -e
      - echo "Cloning GitOps repository..."
      - git clone https://x-access-token:${TOKEN_GITHUB}@github.com/aws-final-6/food-frontend.git
      - cd food-frontend

      - echo "Verifying Kubernetes access..."
      - kubectl get nodes || { echo 'kubectl get nodes failed'; kubectl config view; kubectl config current-context; exit 1; }

  post_build:
    commands:
      - echo "Deployment completed."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
