version: 0.2

env:
  variables:
    GITHUB_REPO: "https://github.com/aws-final-6/GitOps_Repo.git"
    GITHUB_DIR: "GitOps_Repo"
    AWS_REGION: "ap-northeast-2"
    AWS_EKS_REGION: "ap-northeast-2"
    ECR_REGISTRY: "761278642645.dkr.ecr.ap-northeast-2.amazonaws.com"
    TOKEN_GITHUB: "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"
    KUBERNETES_CLUSTER_NAME: "mlr-prd-eks-cls"
    KUBERNETES_NAMESPACE: "default"
  parameter-store:
    TOKEN_GITHUB: "/codebuild/github/token"

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR Public...
      - aws --version
      - export LOGIN_PASSWORD=$(aws ecr-public get-login-password --region $AWS_REGION)
      - echo $LOGIN_PASSWORD | docker login --username AWS --password-stdin $ECR_REGISTRY
      - AWS_ACCESS_KEY_ID=AKIA3CP56HHK356EWBOZ
      - AWS_SECRET_ACCESS_KEY=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
      - ACCOUNT_ID=761278642645

  pre_build:
    commands:
      - echo Pre-build phase started...
      - pwd
      - ls -la
      - GITHUB_COMMIT_HASH=$(git rev-parse --short HEAD)

  build:
    commands:
      - docker build -t aws-school-project7-cicd-aws-repo-GITHUB:$GITHUB_COMMIT_HASH -f Dockerfile .
      - docker tag aws-school-project7-cicd-aws-repo-GITHUB:$GITHUB_COMMIT_HASH $ECR_REGISTRY/aws-school-project7-cicd-aws-repo-GITHUB:$GITHUB_COMMIT_HASH
      - docker tag aws-school-project7-cicd-aws-repo-GITHUB:$GITHUB_COMMIT_HASH $ECR_REGISTRY/aws-school-project7-cicd-aws-repo-GITHUB-latest:latest
      - docker push $ECR_REGISTRY/aws-school-project7-cicd-aws-repo-GITHUB:$GITHUB_COMMIT_HASH
      - docker push $ECR_REGISTRY/aws-school-project7-cicd-aws-repo-GITHUB-latest:latest

 # post_build:
 #   commands:
 #     - echo Updating kubeconfig...
 #     - aws eks --region $AWS_EKS_REGION update-kubeconfig --name $KUBERNETES_CLUSTER_NAME
 #     - cat ~/.kube/config
 #     - kubectl config get-contexts
 #     - echo Deploying to Kubernetes...
 #     - kubectl apply -f deployment.yaml

  artifacts:
    files:
      - '**/*'
    discard-paths: yes
