version: 0.2

phases:
  install:
    commands:
      - echo Setting up AWS CLI credentials...
      - mkdir -p ~/.aws
      - echo "[default]" > ~/.aws/credentials
      - echo "aws_access_key_id=${AWS_ACCESS_SU_ID}" >> ~/.aws/credentials
      - echo "aws_secret_access_key=${AWS_SECRET_SU_KEY}" >> ~/.aws/credentials
      - echo "[default]" > ~/.aws/config
      - echo "region=ap-northeast-2" >> ~/.aws/config
      - cat ~/.aws/credentials
      - cat ~/.aws/config
      - echo Verifying AWS CLI credentials...
      - aws sts get-caller-identity
      - echo Setting up kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mkdir -p /usr/local/bin
      - mv ./kubectl /usr/local/bin/
      - echo kubectl version
      - kubectl version --client
      

  pre_build:
    commands:
      - echo Verifying EKS cluster access...
      - aws eks describe-cluster --region ${AWS_REGION} --name mlr-prd-eks-cls --debug
      - echo Setting up kubeconfig...
      - aws eks update-kubeconfig --region ${AWS_REGION} --name mlr-prd-eks-cls || { echo 'kubeconfig update failed' ; exit 1; }
      - echo "Kubeconfig file contents:"
      - cat ~/.kube/config
      - kubectl config current-context
      - kubectl get nodes

  build:
    commands:
      - echo Cloning GitOps repository...
      - git clone https://x-access-token:${TOKEN_GITHUB}@github.com/aws-final-6/food-frontend.git
      - cd food-frontend
      - echo Verifying Kubernetes access...
      - kubectl get nodes || { echo 'kubectl get nodes failed' ; kubectl config view ; kubectl config current-context ; exit 1; }
      - kubectl config view
      - kubectl config current-context

  post_build:
    commands:
      - echo Deployment completed.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
