apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlr-dev-fe-dpl
  namespace: mlr-dev-fe-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: 192.168.56.200/mylittlerecipebook/busybox:1.31
          command: ['sh', '-c', "until nslookup mlr-dev-be-svc-nod.mlr-dev-be-ns.svc.cluster.local; do echo waiting for backend; sleep 2; done"]
      containers:
        - name: frontend
          image: 192.168.56.200/mylittlerecipebook/mlr-dev-fe-img:24
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: mlr-dev-fe-cm
                  key: API_URL
            - name: FAST_API_URL
              valueFrom:
                configMapKeyRef:
                  name: mlr-dev-fe-cm
                  key: FAST_API_URL
