apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlr-prd-fe-dpl
  namespace: mlr-prd-fe-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: mlr-prd-eks-app-ng
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - frontend
            topologyKey: kubernetes.io/hostname
      initContainers:
        - name: wait-for-backend
          image: 761278642645.dkr.ecr.ap-northeast-2.amazonaws.com/mylittlerecipebook/busybox:1.31
          command: ['sh', '-c', "until nslookup mlr-prd-be-svc-nod.mlr-prd-be-ns.svc.cluster.local; do echo waiting for backend; sleep 2; done"]
      containers:
        - name: frontend
          image: 761278642645.dkr.ecr.ap-northeast-2.amazonaws.com/mylittlerecipebook/mlr-prd-fe-img:9
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: mlr-prd-fe-cm
                  key: API_URL
            - name: FAST_API_URL
              valueFrom:
                configMapKeyRef:
                  name: mlr-prd-fe-cm
                  key: FAST_API_URL